name = "filmweekly"
main = "src/worker.ts"
compatibility_date = "2024-04-03"

[vars]
MODERATION_API_URL = "https://moderation.example.com/v1/analyze"
MODERATION_API_TOKEN = "changeme-moderation-token"
OTP_PEPPER = "6e2bc82427f280c2f7da5215d88b58f437ade807ae8803ebffcc77e7499ea0c4"
SESSION_HS256_SECRET = "3c7f8bbe8bbfccc0fab1e5a6a8aaacf31e7ea2fb6a1b58f101cb03c1e9414073"

[[d1_databases]]
binding = "DB"
database_name = "filmweekly"
database_id = "8ea019d0-59e2-45fd-8bb8-35dfd2da5283"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "filmweekly-assets"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "a3b70b46a9cb401c95fc7f6e290c613d"

[[queues.producers]]
binding = "TASK_QUEUE"
queue = "filmweekly-tasks"

[[queues.consumers]]
queue = "filmweekly-tasks"
max_batch_size = 10
