name = "filmweekly-worker"
main = "src/worker.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "filmweekly"
database_id = "00000000-0000-0000-0000-000000000000"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "filmweekly-assets"

[[kv_namespaces]]
binding = "CONFIG_KV"
id = "00000000000000000000000000000000"

[[queues.producers]]
binding = "TASK_QUEUE"
queue = "filmweekly-tasks"
